
GLOBAL_BEST = 'G'
LOCAL_BEST = 'L'
C1 = 'c1'
C2 = 'c2'
INERTIA = 'w'
NUMBER_NEIGHBORS = 'k'
MINKOWSKI_RULE = 'p'
TYPE = 'type'
OPTIONS = 'options'
X_LABEL_FILTERS = 'n_filtros'
X_LABEL_NEURONS = 'n_neuronios'
Y_LABEL_EPOCHS = 'n_epochs'

SIGMOID = 'sigmoid'
TANH = 'tanh'
RELU = 'relu'